
public class GirişEkranı extends javax.swing.JFrame {

    üyeİşlemleri işlemler = new üyeİşlemleri ();
    public GirişEkranı() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kullaniciAdiAlani = new javax.swing.JTextField();
        sifreAlani = new javax.swing.JPasswordField();
        mesajYazisi = new javax.swing.JLabel();
        girisAlani = new javax.swing.JButton();
        üyeOlmakİcinTiklayiniz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 51));
        setBounds(new java.awt.Rectangle(550, 250, 0, 0));
        setForeground(new java.awt.Color(102, 0, 51));

        jLabel1.setFont(new java.awt.Font("Verdana Pro", 2, 14)); // NOI18N
        jLabel1.setText("Kullanıcı  Adı  :");

        jLabel2.setBackground(new java.awt.Color(102, 0, 51));
        jLabel2.setFont(new java.awt.Font("Verdana Pro", 2, 14)); // NOI18N
        jLabel2.setText("Şifre  :");

        kullaniciAdiAlani.setBackground(new java.awt.Color(0, 102, 102));
        kullaniciAdiAlani.setFont(new java.awt.Font("Verdana Pro", 2, 12)); // NOI18N
        kullaniciAdiAlani.setForeground(new java.awt.Color(204, 204, 204));
        kullaniciAdiAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdiAlaniActionPerformed(evt);
            }
        });

        sifreAlani.setBackground(new java.awt.Color(0, 102, 102));
        sifreAlani.setFont(new java.awt.Font("Verdana Pro", 2, 12)); // NOI18N
        sifreAlani.setForeground(new java.awt.Color(204, 204, 204));

        mesajYazisi.setForeground(new java.awt.Color(102, 0, 102));

        girisAlani.setBackground(new java.awt.Color(0, 102, 102));
        girisAlani.setFont(new java.awt.Font("Verdana Pro", 2, 14)); // NOI18N
        girisAlani.setForeground(new java.awt.Color(102, 0, 0));
        girisAlani.setText("Giriş Yap");
        girisAlani.setActionCommand("");
        girisAlani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisAlaniActionPerformed(evt);
            }
        });

        üyeOlmakİcinTiklayiniz.setText("Üye Olmak İçin Tıklayınız");
        üyeOlmakİcinTiklayiniz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                üyeOlmakİcinTiklayinizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kullaniciAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sifreAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(girisAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(üyeOlmakİcinTiklayiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullaniciAdiAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifreAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mesajYazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(girisAlani, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(üyeOlmakİcinTiklayiniz, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciAdiAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciAdiAlaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciAdiAlaniActionPerformed

    private void girisAlaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisAlaniActionPerformed
        mesajYazisi.setText("") ;
        
        String kullaniciAdi = kullaniciAdiAlani.getText() ;
        String parola = new String (sifreAlani.getPassword()) ;
        boolean girisbasarili = işlemler.girisYap (kullaniciAdi,parola) ;
        
        if (girisbasarili==true) {
           ÜyeEkrani üyeEkrani = new ÜyeEkrani (this,true);
           setVisible (false) ;
           üyeEkrani.setVisible (true) ;
           System.exit(0);
                              
        }
        else {
            mesajYazisi.setText("Giriş başarısız. Tekrar deneyin!") ;
        }
    }//GEN-LAST:event_girisAlaniActionPerformed

    private void üyeOlmakİcinTiklayinizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_üyeOlmakİcinTiklayinizActionPerformed
      
        üyeOlEkrani üyeOl = new üyeOlEkrani (this,true) ;
        setVisible (false) ;
        üyeOl.setVisible(true);
        System.exit(0);
        
        
        
        
        
    }//GEN-LAST:event_üyeOlmakİcinTiklayinizActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirişEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirişEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton girisAlani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField kullaniciAdiAlani;
    private javax.swing.JLabel mesajYazisi;
    private javax.swing.JPasswordField sifreAlani;
    private javax.swing.JButton üyeOlmakİcinTiklayiniz;
    // End of variables declaration//GEN-END:variables
}
